// js/characters.js
// ゲームメタデータ: 80字の読み・敵名・敵バリアント・敵カラー
// GRADE1_KANJI の順番に合わせて並べる

const GRADE1_CHARACTERS = [
  { char: '一', reading: 'いち',   enemyName: 'よこのむし',          enemyVariant: 0, enemyColor: '#e74c3c' },
  { char: '右', reading: 'みぎ',   enemyName: 'みぎてナイト',        enemyVariant: 2, enemyColor: '#c0392b' },
  { char: '雨', reading: 'あめ',   enemyName: 'あめふらしドロップ',  enemyVariant: 3, enemyColor: '#2980b9' },
  { char: '円', reading: 'えん',   enemyName: 'まるまるゴースト',    enemyVariant: 3, enemyColor: '#8e44ad' },
  { char: '王', reading: 'おう',   enemyName: 'おうさまコング',      enemyVariant: 2, enemyColor: '#d4ac0d' },
  { char: '音', reading: 'おと',   enemyName: 'おとひびきバット',    enemyVariant: 1, enemyColor: '#7d3c98' },
  { char: '下', reading: 'した',   enemyName: 'したにもぐるグラブ',  enemyVariant: 1, enemyColor: '#16a085' },
  { char: '火', reading: 'ひ',     enemyName: 'ひのたまデビル',      enemyVariant: 4, enemyColor: '#c0392b' },
  { char: '花', reading: 'はな',   enemyName: 'はなびらフェアリー',  enemyVariant: 0, enemyColor: '#e91e8c' },
  { char: '貝', reading: 'かい',   enemyName: 'かいがらシェル',      enemyVariant: 2, enemyColor: '#1abc9c' },
  { char: '学', reading: 'がく',   enemyName: 'まなびんウィザード',  enemyVariant: 3, enemyColor: '#2471a3' },
  { char: '気', reading: 'き',     enemyName: 'きもちゴースト',      enemyVariant: 3, enemyColor: '#7fb3d3' },
  { char: '九', reading: 'きゅう', enemyName: 'くっつきナイン',      enemyVariant: 0, enemyColor: '#e67e22' },
  { char: '休', reading: 'きゅう', enemyName: 'ねむりんゴースト',    enemyVariant: 3, enemyColor: '#a9cce3' },
  { char: '玉', reading: 'たま',   enemyName: 'たまたまスライム',    enemyVariant: 0, enemyColor: '#27ae60' },
  { char: '金', reading: 'きん',   enemyName: 'きんきらナイト',      enemyVariant: 2, enemyColor: '#d4ac0d' },
  { char: '空', reading: 'そら',   enemyName: 'そらとびドラゴン',    enemyVariant: 4, enemyColor: '#5dade2' },
  { char: '月', reading: 'つき',   enemyName: 'つきみホバー',        enemyVariant: 1, enemyColor: '#9b59b6' },
  { char: '犬', reading: 'いぬ',   enemyName: 'いぬころウルフ',      enemyVariant: 1, enemyColor: '#a04000' },
  { char: '見', reading: 'み',     enemyName: 'みひらきゴースト',    enemyVariant: 3, enemyColor: '#7fb3d3' },
  { char: '五', reading: 'ご',     enemyName: 'ごかくバット',        enemyVariant: 1, enemyColor: '#e67e22' },
  { char: '口', reading: 'くち',   enemyName: 'くちパックン',        enemyVariant: 3, enemyColor: '#1abc9c' },
  { char: '校', reading: 'こう',   enemyName: 'がっこうゴーレム',    enemyVariant: 2, enemyColor: '#5d6d7e' },
  { char: '左', reading: 'ひだり', enemyName: 'ひだりてナイト',      enemyVariant: 0, enemyColor: '#1a5276' },
  { char: '三', reading: 'さん',   enemyName: 'みつのかいぶつ',      enemyVariant: 2, enemyColor: '#f1c40f' },
  { char: '山', reading: 'やま',   enemyName: 'やまのぼりオーク',    enemyVariant: 4, enemyColor: '#7f8c8d' },
  { char: '子', reading: 'こ',     enemyName: 'こどもスライム',      enemyVariant: 0, enemyColor: '#f7dc6f' },
  { char: '四', reading: 'し',     enemyName: 'よつかどゴースト',    enemyVariant: 3, enemyColor: '#a569bd' },
  { char: '糸', reading: 'いと',   enemyName: 'いとまきグラブ',      enemyVariant: 1, enemyColor: '#a93226' },
  { char: '字', reading: 'じ',     enemyName: 'もじもじウィザード',  enemyVariant: 2, enemyColor: '#2471a3' },
  { char: '耳', reading: 'みみ',   enemyName: 'きこえるドラゴン',    enemyVariant: 4, enemyColor: '#1d8348' },
  { char: '七', reading: 'なな',   enemyName: 'なならびバット',      enemyVariant: 1, enemyColor: '#f39c12' },
  { char: '車', reading: 'くるま', enemyName: 'くるまゴーレム',      enemyVariant: 2, enemyColor: '#5d6d7e' },
  { char: '手', reading: 'て',     enemyName: 'てっぽうナイト',      enemyVariant: 0, enemyColor: '#e74c3c' },
  { char: '十', reading: 'じゅう', enemyName: 'じゅうじかスライム',  enemyVariant: 0, enemyColor: '#2ecc71' },
  { char: '出', reading: 'で',     enemyName: 'でてくるデビル',      enemyVariant: 4, enemyColor: '#d35400' },
  { char: '女', reading: 'おんな', enemyName: 'おんなのこフェアリー',enemyVariant: 0, enemyColor: '#e91e8c' },
  { char: '小', reading: 'しょう', enemyName: 'ちびっこスライム',    enemyVariant: 0, enemyColor: '#3498db' },
  { char: '上', reading: 'うえ',   enemyName: 'うえからデビル',      enemyVariant: 3, enemyColor: '#8e44ad' },
  { char: '森', reading: 'もり',   enemyName: 'もりのぬし',          enemyVariant: 4, enemyColor: '#1e8449' },
  { char: '人', reading: 'ひと',   enemyName: 'ひとかたさん',        enemyVariant: 1, enemyColor: '#e74c3c' },
  { char: '水', reading: 'みず',   enemyName: 'みずながれルーパー',  enemyVariant: 0, enemyColor: '#2980b9' },
  { char: '正', reading: 'せい',   enemyName: 'せいかいキング',      enemyVariant: 2, enemyColor: '#27ae60' },
  { char: '生', reading: 'せい',   enemyName: 'いきものドラゴン',    enemyVariant: 4, enemyColor: '#28b463' },
  { char: '青', reading: 'あお',   enemyName: 'あおそらスライム',    enemyVariant: 0, enemyColor: '#1a5276' },
  { char: '夕', reading: 'ゆう',   enemyName: 'ゆうやけゴースト',    enemyVariant: 3, enemyColor: '#e67e22' },
  { char: '石', reading: 'いし',   enemyName: 'いしころゴーレム',    enemyVariant: 2, enemyColor: '#7f8c8d' },
  { char: '赤', reading: 'あか',   enemyName: 'あかほのおデビル',    enemyVariant: 4, enemyColor: '#e74c3c' },
  { char: '千', reading: 'せん',   enemyName: 'せんにんウィザード',  enemyVariant: 1, enemyColor: '#8e44ad' },
  { char: '川', reading: 'かわ',   enemyName: 'かわながれルーパー',  enemyVariant: 0, enemyColor: '#2980b9' },
  { char: '先', reading: 'さき',   enemyName: 'さきがけナイト',      enemyVariant: 2, enemyColor: '#1a5276' },
  { char: '早', reading: 'はや',   enemyName: 'はやてバット',        enemyVariant: 1, enemyColor: '#e67e22' },
  { char: '草', reading: 'くさ',   enemyName: 'くさむらグリーン',    enemyVariant: 0, enemyColor: '#27ae60' },
  { char: '足', reading: 'あし',   enemyName: 'あしながゴーレム',    enemyVariant: 2, enemyColor: '#5d6d7e' },
  { char: '村', reading: 'むら',   enemyName: 'むらびとオーク',      enemyVariant: 4, enemyColor: '#7f8c8d' },
  { char: '大', reading: 'だい',   enemyName: 'おおきなドン',        enemyVariant: 2, enemyColor: '#c0392b' },
  { char: '男', reading: 'おとこ', enemyName: 'おとこのこファイター',enemyVariant: 0, enemyColor: '#2980b9' },
  { char: '竹', reading: 'たけ',   enemyName: 'たけやぶゴースト',    enemyVariant: 3, enemyColor: '#27ae60' },
  { char: '中', reading: 'なか',   enemyName: 'まんなかゴレム',      enemyVariant: 2, enemyColor: '#d35400' },
  { char: '虫', reading: 'むし',   enemyName: 'むしんじゃバグ',      enemyVariant: 1, enemyColor: '#27ae60' },
  { char: '町', reading: 'まち',   enemyName: 'まちなみゴーレム',    enemyVariant: 2, enemyColor: '#7f8c8d' },
  { char: '天', reading: 'てん',   enemyName: 'てんくうドラゴン',    enemyVariant: 4, enemyColor: '#5dade2' },
  { char: '田', reading: 'た',     enemyName: 'でんでんドラゴン',    enemyVariant: 4, enemyColor: '#27ae60' },
  { char: '土', reading: 'つち',   enemyName: 'つちのこゴーレム',    enemyVariant: 2, enemyColor: '#a04000' },
  { char: '二', reading: 'に',     enemyName: 'ふたつめくん',        enemyVariant: 1, enemyColor: '#e67e22' },
  { char: '日', reading: 'にち',   enemyName: 'おひさまゴースト',    enemyVariant: 4, enemyColor: '#f39c12' },
  { char: '入', reading: 'にゅう', enemyName: 'はいりこむスライム',  enemyVariant: 0, enemyColor: '#2c3e50' },
  { char: '年', reading: 'ねん',   enemyName: 'としとりウィザード',  enemyVariant: 3, enemyColor: '#6c3483' },
  { char: '白', reading: 'しろ',   enemyName: 'しろきゴースト',      enemyVariant: 3, enemyColor: '#aab7b8' },
  { char: '八', reading: 'はち',   enemyName: 'はちまきファイター',  enemyVariant: 0, enemyColor: '#e67e22' },
  { char: '百', reading: 'ひゃく', enemyName: 'ひゃくたいゴーレム', enemyVariant: 2, enemyColor: '#5d6d7e' },
  { char: '文', reading: 'ふみ',   enemyName: 'ふみのムシ',          enemyVariant: 1, enemyColor: '#a04000' },
  { char: '木', reading: 'き',     enemyName: 'きのこナイト',        enemyVariant: 2, enemyColor: '#8e5c2a' },
  { char: '本', reading: 'ほん',   enemyName: 'ほんむすびオーク',    enemyVariant: 4, enemyColor: '#5d6d7e' },
  { char: '名', reading: 'な',     enemyName: 'なまえゴースト',      enemyVariant: 3, enemyColor: '#8e44ad' },
  { char: '目', reading: 'め',     enemyName: 'ひとつめこぞう',      enemyVariant: 3, enemyColor: '#2980b9' },
  { char: '立', reading: 'たつ',   enemyName: 'たちあがれナイト',    enemyVariant: 0, enemyColor: '#2c3e50' },
  { char: '力', reading: 'ちから', enemyName: 'ちからもちゴーレム',  enemyVariant: 2, enemyColor: '#922b21' },
  { char: '林', reading: 'はやし', enemyName: 'ふたきりん',          enemyVariant: 0, enemyColor: '#27ae60' },
  { char: '六', reading: 'ろく',   enemyName: 'むっつムシ',          enemyVariant: 1, enemyColor: '#e67e22' },
];
